### ISSUE TITLE
OffsetHeight vs ScrollHeight

### ISSUE THREAD

**Issue by 7iomka** [roginfarrer/collapsed#139]
Hi.
I have a problem with content that have that type of layout
```
<section {...ssrCollapseProps}>
 <div>
   <div style={{ marginRight: '-15px', marginBottom: '-15px' }}>
      <div style={{ marginRight: '15px', marginBottom: '15px' }}>1</div>
      <div style={{ marginRight: '15px', marginBottom: '15px' }}>2</div>
   </div>
 </div>
</section>

```

Section will have
- scrollHeight: expected height + 15px
- offsetHeight: expected height

Because of this, for this type of content we have a jump.
Possible fix
- Add prop that force usage offsetHeight instead of scrollHeight

Why can such a layout be encountered and nothing can be done about it?
In our project, for example, this layout is used as fallback for `gap` property which was added to support only in safari 14.1 (and mobile safari 14.5) and we want to support users in earlier versions. Also similar styles can be found in components such as `Row` from bootstrap which uses the same approach for more support.

Many thanks!

**Comment by 7iomka** [comment]
In this example you can see useCases on of which has described issues - scrollHeight is more than we expected and we have a jump when collapse content opens

https://codepen.io/7iomka/pen/xxajRLe?editors=1010

**Comment by roginfarrer** [comment]
Hmm I think you're right that `offsetHeight` would be the appropriate measurement. I can't remember why I went with `scrollHeight`, I didn't document those edge cases. I'll do some testing to make sure that there's nothing funny with `offsetHeight`.

**Comment by roginfarrer** [comment]
After some testing, I actually think `scrollHeight` is the appropriate measurement. I'm not sure if there is a way to support this edge case.

We use `scrollHeight` because that will measure the size of the content, regardless of whether it's visible. This is necessary because prior to the expand animation, we need to measure the size of the element *before* we transition open. In this case `offsetHeight` will always be `0`, while `scrollHeight` gives us the full dimension, even if it's not visible.

Margin of the internal elements do not take up space of the containing element. This is apparent if you make the background of the collapse element red, but you can inspect the children and see the margin taking up space within it.

<img width="325" alt="CleanShot 2023-03-24 at 22 25 04@2x" src="https://user-images.githubusercontent.com/9063669/227698135-b73c70db-cb15-4aa8-89c0-6b04fa26d612.png">
