### ISSUE TITLE
Read more effect

### ISSUE THREAD

**Issue by eternity4318** [roginfarrer/collapsed#160]
Is there a way to make a read more affect (possibly by making collapsed height prop a percentage)?

**Comment by roginfarrer** [comment]
After doing a deep-dive into how one might make this, I've found that the easiest solution would be two nest a second instance of a collapse within another. It gets really complicated to handle 3 states for the collapse. 

The implementation would look [something like this](https://react-collapsed.netlify.app/?path=/story/nested-collapses--nested). But instead of deliberately segmenting the content, you'd use the `collapsedHeight` option to something like `200`, or whatever you'd like to collapse it too.

**Comment by menachem1** [comment]
Thank you so much.

**Comment by menachem1** [comment]
Is there a way to make that the nested component when expanded should not go on the next line (using span messes up the animation)
